### ISSUE TITLE
Syntax error on start

### ISSUE THREAD

**Issue by lokiagent** [Ataraksia/NeweggBot#23]
Followed the install instructions, but I get the following on trying to start:

Documents\NeweggBot\NeweggBot.js:7
<!DOCTYPE html>
^

SyntaxError: Unexpected token '<'
←[90m    at wrapSafe (internal/modules/cjs/loader.js:979:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1027:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m

**Comment by lokiagent** [comment]
Nevermind. I'm not very bright sometimes.
