### ISSUE TITLE
Error on MacOS

### ISSUE THREAD

**Issue by mrhelium3** [Ataraksia/NeweggBot#34]
When I try to run the code.. I get this error. 

`Wed Dec 23 2020 20:44:33 : Started
(node:17034) UnhandledPromiseRejectionWarning: Error: Could not find browser revision latest. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
    at FirefoxLauncher.launch (/Users/----/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:193:23)
    at async run (/Users/----/Desktop/NeweggBot-master/neweggbot.js:38:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17034) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17034) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by mrweiner** [comment]
Did you follow the installation instructions? They address this directly.
> After installing via git or by downloading the code and extracting it, navigate to the folder where the files are located via powershell(or equivalent console) and run npm install puppeteer -PUPPETEER_PRODUCT=firefox. If you end up experiencing the error Error: Could not find browser revision latest when running, you may also need to run the command PUPPETEER-PRODUCT=firefox npm i puppeteer.

In fact, your error tells you how to fix it.
> Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.

**Comment by mrhelium3** [comment]
Hey! Thanks for following up. Yes I did follow what the instruction/readme said and the fix in the error message. I should have clarified that.

**Comment by wcedmisten** [comment]
There is currently a typo in the README, so if you used `PUPPETEER-PRODUCT=firefox` (with a hyphen) you might still get this error. Could you try running it with `PUPPETEER_PRODUCT=firefox` (with an underscore).

Also, the firefox download took a while for me and seemed stuck before it ultimately completed, did the download definitely complete?

**Comment by CarsonCG** [comment]
There might be some path issue. I found changing the product to 'chrome' from 'firefox' worked just fine on mac without having to deal with exporting app ids and stuff. 
(i.e
`
const browser = await puppeteer.launch({
        headless: false,
	product: 'chrome',
        defaultViewport: { width: 1280, height: 720 }
});
`
instead of 
`
const browser = await puppeteer.launch({
        headless: false,
	product: 'firefox',
        defaultViewport: { width: 1280, height: 720 }
});
`
as seen in lines 38-42 in the original script.)
