### ISSUE TITLE
Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by lemkeant** [Ataraksia/NeweggBot#4]
Hi,

Having an issue getting this launched, seems to be different vs your previous merged request? The edited install flag doesnt seem to do much for me. Im on Windows

(node:20676) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!

    at onClose (C:\Desktop\NeweggBot-master\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:193:20)
    at Interface.<anonymous> (C:\Desktop\NeweggBot-master\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:183:68)
    at Interface.emit (events.js:326:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by Codolophier** [comment]
Have you come across this Puppeteer issue/resolution yet?

https://github.com/puppeteer/puppeteer/issues/5958

**Comment by lemkeant** [comment]
I did remember looking at that. At this point, I've got things shored up on a totally different machine, so I'll plan to close this since nothing much seemed to come of it.
