### ISSUE TITLE
 TimeoutError: waiting for selector `#term` failed: timeout 5000ms exceeded

### ISSUE THREAD

**Issue by Yuniecorn** [Ataraksia/NeweggBot#41]
Aside: I have little experience with JS. 

Script is unable to press "Continue to Payment" button to propagate the payment section of checkout.

Config: auto_sumbit - True

Powershell Log:
Thu Jan 07 2021 10:03:21 : Started
Thu Jan 07 2021 10:03:36 : Manual authorization code required by Newegg.  This should only happen once.
Thu Jan 07 2021 10:03:47 : Logged in
Thu Jan 07 2021 10:03:47 : Checking for card
Thu Jan 07 2021 10:03:50 : Card added to cart, attempting to purchase
Thu Jan 07 2021 10:03:50 : Starting Secure Checkout
Thu Jan 07 2021 10:03:57 : TimeoutError: waiting for selector `#term` failed: timeout 5000ms exceeded
(node:1200) UnhandledPromiseRejectionWarning: Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (C:\Users\Admin\Desktop\NeweggBot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:329:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ElementHandle.click (C:\Users\Admin\Desktop\NeweggBot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:390:26)
    at async DOMWorld.click (C:\Users\Admin\Desktop\NeweggBot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:277:9)
    at async run (C:\Users\Admin\Desktop\NeweggBot-master\neweggbot.js:154:3)

(Use `node --trace-warnings ...` to show where the warning was created)

(node:1200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:1200) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

![NewEgg Capture](https://user-images.githubusercontent.com/77113210/103908914-0d82e080-50d1-11eb-8051-a370acf53485.PNG)

**Comment by northmatt** [comment]
Should be fixed in PR [35](https://github.com/Ataraksia/NeweggBot/pull/35) and [43](https://github.com/Ataraksia/NeweggBot/pull/43)
